### ISSUE TITLE
Command to return random color pallete along with image.

### ISSUE THREAD

**Issue by p014ri5** [p014ri5/scylla#2]
Make a command to return a random color pallete with an image. Something like [coolors.co](coolors.co). You can use [Pillow](https://pypi.org/project/Pillow/) python library to generate images. Also try to take a number of colors as argument with a finite limit.

**Comment by jyoungiv** [comment]
Hello, I would like to contribute, may I be assigned to this issue?

**Comment by p014ri5** [comment]
There you go! Thanks for showing interest :)
