### ISSUE TITLE
Command to implement Bulls and Cows game along with Rock Papers Scissors!

### ISSUE THREAD

**Issue by p014ri5** [p014ri5/scylla#3]
In general cog make a bulls and cows game. Read more about the game [here](https://en.wikipedia.org/wiki/Bulls_and_Cows). Also make a Simple rock paper scissors game using random module.

**Comment by roopeshvs** [comment]
I'd love to work on this.

**Comment by p014ri5** [comment]
Great!

**Comment by AxSmasher44** [comment]
Hey, I would like to work on this too!

**Comment by p014ri5** [comment]
@AxSmasher44 I'll Assign this to you too.. Best one gets merged! :D

**Comment by roopeshvs** [comment]
These are be separate commands, right?
Let me do Bulls and Cows.
And @AxSmasher44 can do Rock. Paper. Scissors?

**Comment by AxSmasher44** [comment]
Yeah sure, this is gonna be a text-based rock paper scissors or what?

**Comment by p014ri5** [comment]
Yeah cool! Yup its text based rps game 👍🏻

**Comment by ruchijain4** [comment]
Hey! I would love to work on this.

**Comment by p014ri5** [comment]
Sadly this issue got taken :( ! But you can still work on this, As I said earlier Best one get merged! Anyway Hacktoberfest doesn't require merged PR's :D I am going to assign you this..
