### ISSUE TITLE
Command that returns time of the given city as a argument.

### ISSUE THREAD

**Issue by p014ri5** [p014ri5/scylla#4]
Make a command that will take city as an argument and return Date, Day, Time, Weekday along with timezone (GMT).

**Comment by Apoorve73** [comment]
Since it is developed in python, I would love to work on this. Please explain, in which file you want changes to be made.
:+1:

**Comment by p014ri5** [comment]
Well it is in General Cog. i.e. it is located in bot/cogs/general/general.py . Have fun developing this :)

**Comment by Apoorve73** [comment]
Super Cool :sparkle: This can be the best way I can start with a Discord Bot. Haha! Even my Telegram Bot's dynos have been consumed.
