### ISSUE TITLE
Command to return Mozilla docs and React docs link based on arguments taken.

### ISSUE THREAD

**Issue by p014ri5** [p014ri5/scylla#5]
Take an argument to the command and get links to react and MDN web docs using argument as query. Vue docs implementation will also be appreciated. :D You can use [Algoliasearch](https://pypi.org/project/algoliasearch/) for this. You are also free to implement all the supported types in algoliasearch. If you would like to see a sample program You should check out [https://github.com/brpaz/ulauncher-docsearch/blob/master/docsearch/searcher.py]

**Comment by MostDeadDeveloper** [comment]
Sounds like an interesting idea, can I work on this as well?

**Comment by p014ri5** [comment]
Sure! :D

**Comment by MostDeadDeveloper** [comment]
has this been resolved?
